language: scala
scala:
  - 2.12.4
env:
  - akkaVersion=2.5.11
  - akkaVersion=2.5.10
  - akkaVersion=2.5.9
  - akkaVersion=2.5.8
  - akkaVersion=2.5.7
  - akkaVersion=2.5.6
  - akkaVersion=2.5.5
  - akkaVersion=2.5.4
script:
  - sbt ++$TRAVIS_SCALA_VERSION -DakkaVersion=$akkaVersion ';akkaVersion ;test'